server:
  port: 8080

spring:
  application:
    name: encrypt-api
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fxgmall?characterEncoding=UTF8&useSSL=false
    hikari:
      max-lifetime: 180000
  redis:
    host:
    port:
    password:


logging:
  level:
    org:
      springframework:
        security: info


