server:
  port: 8080

spring:
  application:
    name: archetype-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fxgmall?characterEncoding=UTF8&useSSL=false
    hikari:
      max-lifetime: 180000
  redis:
    host:
    port:
    password:
  task:
    execution:
      pool:
        allow-core-thread-timeout: true
        core-size: 3
        max-size: 3
        queue-capacity: 5000
      thread-name-prefix: ASYNC-TASK-
    scheduling:
      pool:
        size: 3
      thread-name-prefix: SCHEDULING-TASK-

#mybatis:
#  configuration:
#    default-enum-type-handler: com.fxg.archetype.configs.AutoEnumTypeHandler 这里配置枚举转换器会被mybatis-plus覆盖

mybatis-plus:
  mapper-locations: classpath*:mapperXML/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    default-enum-type-handler: com.fxg.archetype.configs.AutoEnumTypeHandler

logging:
  level:
    org:
      springframework:
        security: info


rsa:
  encrypt:
    open: true # 是否开启加密 true  or  false
    showLog: true # 是否打印加解密log true  or  false
    timestampCheck: true # 是否开启时间戳检查 ture or false
    publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAM9E/1y69INmPhBBjZ6MGATDRp+NIqWkRNwpVOKtiqZcchOU6i7M/y3HDL8n03lpTFSjTA0cuU5jfE+l+kiFVIsCAwEAAQ==

    privateKey: MIIBVwIBADANBgkqhkiG9w0BAQEFAASCAUEwggE9AgEAAkEAz0T/XLr0g2Y+EEGNnowYBMNGn40ipaRE3ClU4q2KplxyE5TqLsz/LccMvyfTeWlMVKNMDRy5TmN8T6X6SIVUiwIDAQABAkEAhzzExbNyYN3wNtke10kfTtQ/G1GSPrO8/k21hiWnZr2UHeU97NYyP3+2ct49iAjguQrpG9bsw4AjoSuQgnQPaQIhAO8q6jfw8Kl4A/ZRpLyDKkRGyT1ZFw1LncFfiN32MSgHAiEA3dtfv8DYJ9E6xPHHjUtsZo4/AV2/J/z4x1EUhYPRZl0CIQCgTwufY4hsj11YhXD+SozSJwBMdqLU7pJXQ0niPVrFkQIhAKSv+Ra1x39fMJoLxI8dYv2KMDkKZyD/B4mlpW8rF+E9AiEAwSKOXJoUaRGb02/syD2JjneUbiQdWAajJxyrU7vb6g0=